### PR TITLE
Standard Markdown needed in project root

### PR DESCRIPTION
**Pull request by HuckCollective**
Some obsidian markdown will not work in GitHub preview, I was trying to use embeds in the readme.md  and this will not work, I updated the project root md files to use markdown standard links

### CODE REVIEW

**Comment by genemerrill** [comment]
@webvpro I pulled up the vault in Obsidian and did a spot check. This commit removes the dupe LICENSE file and updates link in ToC to point at CSOL. Whattdya think?

**Review by HuckCollective — COMMENTED** [review]
Looks Good can you approve?

**Comment by genemerrill** [comment]
@webvpro merged and closed

**Review by genemerrill — COMMENTED** [review]
Double checked with webvpro

**Pull request merged**
